# CasaVue configuration file

# appearance settings
customization:

  # influences page title and PWA name
  name: Your Text!

  colors:
    # main color
    theme: "#deaded"

    # color settings for dashboard items
    items:
      # range: 0 <-> 100
      saturation: 8

      # range: -1 <-> 100
      # set lightness to -1 to use browser theme setting
      lightness: 84

# including or excluding items or namespaces by regex
content_filters:

  namespace:
    
    # possible values: "include", "exclude"
    mode: "include"
      
    # Go regexp syntax compatible (https://pkg.go.dev/regexp/syntax)
    # catches all values by default
    pattern: "^.*$"

  item:

    # possible values: "include", "exclude", "ingressAnnotation"
    # "ingressAnnotation" mode disables item regex pattern, and includes only 
    # ingress resources with casavue.app/enable=true annotation
    mode: "include"

    # Go regexp syntax compatible (https://pkg.go.dev/regexp/syntax)
    # catches all values by default
    pattern: "^.*$"
    
# Allows connections to servers with an invalid TLS certificate
# Don't turn it on unless you know what you're doing
allow_skip_tls_verify: true

logging:

  # possible levels: "debug", "info", "warn", "error"
  level: "info"
